# docker/docker-compose.yml

version: "3.9"

services:

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: yomaseru_backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - mcp
      - ollama
    volumes:
      - ../backend:/app/backend  # hot reload (dev)
    restart: always

  mcp:
    build:
      context: ..
      dockerfile: docker/mcp.Dockerfile
    container_name: yomaseru_mcp
    ports:
      - "9000:9000"
    env_file:
      - ../.env
    volumes:
      - ../mcp_server:/app/mcp_server
    restart: always

  postgres:
    build:
      context: ..
      dockerfile: docker/postgres.Dockerfile
    container_name: yomaseru_postgres
    environment:
      DB_NAME: ${DB_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend-streamlit.Dockerfile
    container_name: yomaseru_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ../frontend_streamlit:/app/frontend_streamlit
    restart: always

  ollama:
    image: ollama/ollama
    container_name: yomaseru_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

volumes:
  postgres_data:
  ollama_data: